general.import = [
	"~/.config/alacritty/gruvbox-dark.toml"
]
general.live_config_reload = true

[terminal.shell]
program = "/bin/bash"  # or bash, fish, whatever you use
args = ["-c", "zellij"]

[font]
    size = 10.0

[window]
    opacity = 0.9
    padding.x = 10
    padding.y = 10
    dynamic_padding = false
